/*
Copyright © 2023 João Freire <jvwfreire@gmail.com>
*/
package cmd

import (
	"fmt"

	utils_aave "main/utils/aave"
	utils_compound "main/utils/compound"

	"github.com/spf13/cobra"
)

// queryHealthCmd represents the queryHealth command
var queryHealthCmd = &cobra.Command{
	Use:   "queryHealth",
	Short: "Queries the collateral/borrow health of a list of users",
	Long: `Queries the borrow positions health factor at AAVE-v2 lending pool and outputs
users with a health factor lower than 1.5 in red, alongside with their addresses.
To run this command, you need to have a .csv file with the following format:
"txHash, address, blockNumber".

This file can be generated by running the command "borrowerList".
	`,
	Args: cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		if args[0] == "aave" {
			fmt.Println("Querying AAVE V2 health factor...")
			utils_aave.QueryHealth()
		} else if args[0] == "compound" {
			fmt.Println("Querying Compound V3 health factor...")
			utils_compound.QueryHealth()
		} else {
			fmt.Println("Invalid argument. Please use 'aave' | 'compound' as the argument.")
		}

	},
}

func init() {
	rootCmd.AddCommand(queryHealthCmd)

	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// queryHealthCmd.PersistentFlags().String("foo", "", "A help for foo")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	// queryHealthCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}
